spring:
  profiles:
    active: local
  datasource:
#    url: jdbc:mariadb://web-back-test.cewzughkzm66.ap-northeast-2.rds.amazonaws.com/back
#    username: admin
#    password: 12341234
#    driver-class-name: org.mariadb.jdbc.Driver

    url: jdbc:h2:tcp://localhost/~/greentech
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jwt:
    secret: asusoftjwt

  jpa:
    hibernate:
#      TODO: - 서버 업로드시 none 으로 변경할 것
      ddl-auto: none
#      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
#        default_batch_fetch_size: 500
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging.level:
#  root: debug
  org.hibernate.SQL: info
  # org.hibernate.type: trace

server:
  http2:
    enabled: true
  port: 443
  ssl:
    enabled: true
    key-store: classpath:bootsecurity.p12
    key-store-password: '@asus@'
    key-store-type: PKCS12
    key-alias: bootsecurity